name: cashflow
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Matches Flutter 3.29.0 and allows upgrades

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4  # Updated to latest
  english_words: ^4.0.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.1.2
  intl: ^0.20.2  # Updated to latest
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9 

flutter:
  uses-material-design: true
  assets:
    - .env