name: Backend CI/CD

on:
  push:
    branches: [backend-dev]
  pull_request:
    branches: [backend-dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile.backend
          push: true
          tags: siddankthep/cashflow-backend:latest

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., us-east-1

      # Get GitHub Actions runner IP
      - name: Get Runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      # Add runner IP to security group
      - name: Add Runner IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # Deploy to EC2
      - name: Deploy backend to EC2
        env:
          EC2_IP: ${{ secrets.AWS_EC2_IP }}
          EC2_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            docker stop cashflow-backend || true
            docker rm cashflow-backend || true
            docker pull siddankthep/cashflow-backend:latest
            docker run -d -p 8080:8080 -v /home/ubuntu/cashflow/receipt-images:/app/receipt-images --env-file cashflow/backend/.env --name cashflow-backend siddankthep/cashflow-backend:latest
          EOF
          rm key.pem

      # Remove runner IP from security group
      - name: Remove Runner IP from Security Group
        if: always() # Runs even if previous steps fail
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
